import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

import { describe, expect, it } from "vitest";

/**
 * GL-83: the SPA never cites a document section by *number*. A comment names the document and the
 * heading text — `ARCHITECTURE.md "Reservation privacy"` — never a section number.
 *
 * This is the web half of the .NET architecture rule of the same name
 * (`{Service}.UnitTests/Architecture/CitationRuleTests.cs`) — a hand-maintained twin, not a synced
 * copy, since no script can copy C# into TypeScript and after GL-25 the two live in different
 * repos. `GENERATED_MARKERS` below is duplicated there verbatim and both probes iterate it, so a
 * marker added to one twin and not the other shows up as a diff. What must stay in step and what
 * deliberately differs is written down in `scripts/sync-arch-tests.sh`'s header. It exists as a test rather than
 * an eslint rule for two reasons: eslint does not lint comments, and this has to cover
 * `package.json`, `Dockerfile` and `README.md` too. It survives the GL-25 split, where `web/`
 * becomes its own repo with no .NET tests in it at all.
 *
 * It sits at the web root rather than under `src/` on purpose: it reads the filesystem, and
 * `tsconfig.app.json` deliberately gives `src/` only `vite/client` types, so node's `fs` is not
 * — and should not become — visible to application code. Here it belongs to
 * `tsconfig.node.json` instead, alongside `vite.config.ts`.
 *
 * The web files were where the wrong citations were easiest to see when this was written: nine
 * of the repo's ten references to a CONVENTIONS.md section that does not exist were here (the
 * privacy rules live in ARCHITECTURE.md, and always have), plus one to the conventions *skill*,
 * whose section numbers GL-77 deliberately deleted. Repo-wide the count was far worse — 118 of
 * 759 citations were pointing at the wrong section, and only 13 of those were danglers a script
 * could have found; the rest named a real section that was not the one meant, which is why they
 * had survived twenty batches. Every one of them looked right as a number.
 *
 * This file contains no section sign and does not exempt itself: the banned character is written
 * as a `\u00A7` escape and named in prose as U+00A7 throughout. An exempted file is a hole.
 */

const SECTION_SIGN = "\u00A7";
// U+FFFD, written as an escape for the same reason SECTION_SIGN is: a literal here would
// make this file exclude itself from its own scan. It did, once, before this comment.
const REPLACEMENT_CHARACTER = "\uFFFD";
// Vitest's jsdom environment rewrites `import.meta.url` to a non-file URL, so the walk roots
// on the runner's working directory — which Vitest sets to the config root, i.e. web/. If that
// ever stops being true the population assertions below fail loudly rather than scanning the
// wrong tree quietly.
const WEB_ROOT = process.cwd();
const SKIPPED_DIRECTORIES = new Set([
  "node_modules",
  "dist",
  ".git",
  "coverage",
]);
const MAX_FILE_BYTES = 1024 * 1024;

/**
 * A file is generated if it says so in its own first lines. Path-based detection was rejected
 * back when this repo generated its own protobuf client into `src/gen/`: a rule keyed on one
 * generator's output directory silently stops covering the next generator someone adds. GL-25
 * moved that generator to giftlist-gateway, which vindicates the choice — the path this rule
 * would have been keyed on no longer exists here, and the rule needed no edit.
 */
const GENERATED_MARKERS = ["@generated", "<auto-generated"];

function isGenerated(text: string): boolean {
  const header = text.split("\n", 5);
  return GENERATED_MARKERS.some((marker) =>
    header.some((line) => line.includes(marker)),
  );
}

function textFilesUnder(directory: string): { path: string; text: string }[] {
  const found: { path: string; text: string }[] = [];

  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const absolute = join(directory, entry.name);

    if (entry.isDirectory()) {
      if (!SKIPPED_DIRECTORIES.has(entry.name)) {
        found.push(...textFilesUnder(absolute));
      }
      continue;
    }

    if (!entry.isFile() || statSync(absolute).size > MAX_FILE_BYTES) {
      continue;
    }

    const bytes = readFileSync(absolute);
    const text = bytes.toString("utf8");
    // A replacement character means the bytes were not UTF-8 text — an image, a lockfile binary.
    // Deciding "is this text?" by decoding rather than by an extension allowlist is deliberate:
    // an allowlist is a list to forget to add to, and the point of this rule is that the next
    // kind of file is covered too.
    if (text.includes(REPLACEMENT_CHARACTER) || isGenerated(text)) {
      continue;
    }

    found.push({
      path: relative(WEB_ROOT, absolute).replace(/\\/g, "/"),
      text,
    });
  }

  return found;
}

describe("citations", () => {
  it("Source_ShouldNeverCiteADocumentSectionByNumber", () => {
    // Arrange
    const scanned = textFilesUnder(WEB_ROOT);

    // Act
    const offenders = scanned
      .filter((file) => file.text.includes(SECTION_SIGN))
      .map(
        (file) =>
          `${file.path}:${file.text.slice(0, file.text.indexOf(SECTION_SIGN)).split("\n").length}`,
      );

    // Assert
    // The population half first: a walk that reaches nothing passes this vacuously and looks
    // exactly like a clean repo. These pin that it reaches this file, page source, and the
    // non-source files at the root that carried citations too.
    expect(scanned.length).toBeGreaterThanOrEqual(10);
    expect(scanned.map((f) => f.path)).toContain("citations.test.ts");
    expect(
      scanned.some((f) => f.path.startsWith("src/") && f.path.endsWith(".tsx")),
    ).toBe(true);
    expect(scanned.map((f) => f.path)).toContain("package.json");

    expect(
      offenders,
      "U+00A7 SECTION SIGN appears in source (GL-83). Cite the document and the heading text " +
        'instead of a section number — ARCHITECTURE.md "Reservation privacy", not ' +
        "ARCHITECTURE.md followed by a number: the number rots silently and gets copied outward, " +
        "the heading does not.",
    ).toEqual([]);
  });

  it("TheGeneratedFileFilter_ShouldJudgeKnownHeadersCorrectly", () => {
    // Arrange
    // The exclusion above is the one hole in this rule, so what counts as "generated" is pinned
    // here rather than left to whatever directory a future generator writes into.
    const handWritten = 'import { describe } from "vitest";\n';
    const markerBelowTheHeader =
      "// a hand-written file\n".repeat(20) +
      "// ...which says @generated far below its header.\n";

    // Act
    const judgements = Object.fromEntries([
      ...GENERATED_MARKERS.map((marker) => [
        marker,
        isGenerated(`// ${marker} by some tool\n`),
      ]),
      ["hand-written", isGenerated(handWritten)],
      ["marker below the header", isGenerated(markerBelowTheHeader)],
    ]);

    // Assert
    // The list itself first: emptied or edited down, every judgement below still passes while the
    // exclusion silently stops matching. Spelled out here and in CitationRuleTests.cs, its
    // hand-maintained twin, so the two cannot drift without one of them going red.
    expect(GENERATED_MARKERS).toEqual(["@generated", "<auto-generated"]);
    expect(judgements).toEqual({
      ...Object.fromEntries(GENERATED_MARKERS.map((marker) => [marker, true])),
      "hand-written": false,
      "marker below the header": false,
    });
  });
});
