/**
 * Mantine theme derived from `mockups/style.css` (GL-121) — the six mockup HTML files and
 * `mockups-png/*.png` are the visual reference; this file turns their `:root` custom properties
 * into Mantine's theme shape rather than re-deriving them from the screenshots by eye.
 *
 * `primary` and `accent` are hand-generated 10-shade tuples centred on `--primary`/`--accent`
 * (see the tuples' own comments below for how shade 6/7/0 map to the mockup's
 * `--primary`/`--primary-hover`/`--primary-soft` and `--accent`/`--accent-soft`) — deliberately
 * not an alias of Mantine's built-in `violet`, which is a different hue and a different curve.
 *
 * `other` carries the mockup's remaining `:root` variables (`--bg`, `--surface`, `--border`,
 * `--text`, `--text-muted`) that don't correspond to a Mantine theme concept, so a component reads
 * `useMantineTheme().other.textMuted` instead of a scattered hex literal. `cssVariablesResolver`
 * below mirrors the same values into CSS custom properties (`--gl-*`, plus overriding Mantine's
 * own `--mantine-color-body`/`--mantine-color-text`) for the handful of places that need them in
 * plain CSS rather than a component prop — `AuthCard`'s radial-gradient page background is the
 * one example this story adds.
 */
import { createTheme, type CSSVariablesResolver } from "@mantine/core";

// Centred on --primary (#5b3df0, shade 6) and --primary-hover (#4a2fd6, shade 7 — Mantine's
// default light-mode hover shade is primaryShade + 1). Shade 0 matches --primary-soft (#efeafd)
// exactly; shades 1–5 and 8–9 are generated by interpolating hue-250 HSL between/around those
// three fixed points, not picked by eye.
const primary = [
  "#efeafd",
  "#dbd5fb",
  "#c4baf9",
  "#a08ff5",
  "#816bf3",
  "#6b51f1",
  "#5b3df0",
  "#4a2fd6",
  "#391fbd",
  "#2e199a",
] as const;

// Centred on --accent (#ff7a59, shade 6) and --accent-soft (#fff0eb, shade 0) — the countdown and
// eyebrow uses in the mockups. No hover value is defined for accent in style.css, so shades 7–9
// continue the same hue-12 HSL curve rather than anchoring a fourth fixed point.
const accent = [
  "#fff0eb",
  "#ffe1d9",
  "#ffcec2",
  "#ffb19d",
  "#ff997f",
  "#ff8769",
  "#ff7a59",
  "#ff582e",
  "#ff3705",
  "#db2c00",
] as const;

export const theme = createTheme({
  primaryColor: "primary",
  // Both schemes pinned to shade 6 rather than Mantine's default { light: 6, dark: 8 } — light is
  // the only scheme this story wires up (forceColorScheme="light" in App.tsx), and a single number
  // keeps the primary-shade story consistent if dark mode is ever turned on without a design pass.
  primaryShade: 6,
  colors: { primary, accent },
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Inter, Roboto, sans-serif',
  defaultRadius: "md",
  radius: {
    xs: "4px",
    sm: "8px",
    // Buttons and inputs use theme.defaultRadius ("md") unless a component passes its own
    // `radius` prop — mockups/style.css's .btn/.field input are 8–9px; "~10px" per GL-121.
    md: "10px",
    // Cards (AuthCard, and later the dashboard/list-detail cards) pass radius="lg" explicitly to
    // reach this — mockups/style.css's --radius (14px), the one thing a shared "md" couldn't also
    // be without conflating two different mockup values into one theme key.
    lg: "14px",
    xl: "20px",
  },
  shadows: {
    xs: "0 1px 2px rgba(36, 31, 54, 0.04)",
    sm: "0 1px 2px rgba(36, 31, 54, 0.04)",
    md: "0 1px 2px rgba(36, 31, 54, 0.04), 0 8px 24px rgba(36, 31, 54, 0.06)",
    lg: "0 1px 2px rgba(36, 31, 54, 0.04), 0 8px 24px rgba(36, 31, 54, 0.06)",
    xl: "0 1px 2px rgba(36, 31, 54, 0.04), 0 8px 24px rgba(36, 31, 54, 0.06)",
  },
  other: {
    bg: "#f6f5fb",
    surface: "#ffffff",
    border: "#e4e1f0",
    text: "#241f36",
    textMuted: "#6b647f",
  },
});

// Overrides Mantine's own --mantine-color-body/--mantine-color-text (baseline.css already applies
// both to <body>, so this alone satisfies GL-121's "body background/text" requirement with no
// hand-written CSS) and adds --gl-* aliases for `other`'s remaining values, for the few call sites
// that need a CSS custom property rather than a theme prop (AuthCard's page background gradient).
export const cssVariablesResolver: CSSVariablesResolver = (resolvedTheme) => ({
  variables: {
    "--mantine-color-body": resolvedTheme.other.bg,
    "--mantine-color-text": resolvedTheme.other.text,
    "--gl-bg": resolvedTheme.other.bg,
    "--gl-surface": resolvedTheme.other.surface,
    "--gl-border": resolvedTheme.other.border,
    "--gl-text": resolvedTheme.other.text,
    "--gl-text-muted": resolvedTheme.other.textMuted,
  },
  light: {},
  dark: {},
});
