/**
 * Mantine theme derived from `mockups/style.css` (GL-121) — the six mockup HTML files and
 * `mockups-png/*.png` are the visual reference; this file turns their `:root` custom properties
 * into Mantine's theme shape rather than re-deriving them from the screenshots by eye.
 *
 * `primary` and `accent` are hand-generated 10-shade tuples centred on `--primary`/`--accent`
 * (see the tuples' own comments below for how shade 6/7/0 map to the mockup's
 * `--primary`/`--primary-hover`/`--primary-soft` and `--accent`/`--accent-soft`) — deliberately
 * not an alias of Mantine's built-in `violet`, which is a different hue and a different curve.
 *
 * `other` carries the mockup's remaining `:root` variables (`--bg`, `--surface`, `--border`,
 * `--text`, `--text-muted`) that don't correspond to a Mantine theme concept, so a component reads
 * `useMantineTheme().other.textMuted` instead of a scattered hex literal. `cssVariablesResolver`
 * below mirrors the same values into CSS custom properties (`--gl-*`, plus overriding Mantine's
 * own `--mantine-color-body`/`--mantine-color-text`) for the handful of places that need them in
 * plain CSS rather than a component prop — `AuthCard`'s radial-gradient page background is the
 * one example this story adds.
 */
import { createTheme, type CSSVariablesResolver } from "@mantine/core";

// Centred on --primary (#5b3df0, shade 6) and --primary-hover (#4a2fd6, shade 7 — Mantine's
// default light-mode hover shade is primaryShade + 1). Shade 0 matches --primary-soft (#efeafd)
// exactly; shades 1–5 and 8–9 are generated by interpolating hue-250 HSL between/around those
// three fixed points, not picked by eye.
const primary = [
  "#efeafd",
  "#dbd5fb",
  "#c4baf9",
  "#a08ff5",
  "#816bf3",
  "#6b51f1",
  "#5b3df0",
  "#4a2fd6",
  "#391fbd",
  "#2e199a",
] as const;

// Centred on --accent (#ff7a59, shade 6) and --accent-soft (#fff0eb, shade 0) — the countdown and
// eyebrow uses in the mockups. No hover value is defined for accent in style.css, so shades 7–9
// continue the same hue-12 HSL curve rather than anchoring a fourth fixed point.
const accent = [
  "#fff0eb",
  "#ffe1d9",
  "#ffcec2",
  "#ffb19d",
  "#ff997f",
  "#ff8769",
  "#ff7a59",
  "#ff582e",
  "#ff3705",
  "#db2c00",
] as const;

// Shared by body text and headings: Mantine's `headings.fontFamily` is a separate default that
// would otherwise skip Inter on a non-Apple demo box (Batch 42 review, H1).
const fontFamily =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", Inter, Roboto, sans-serif';

// Centred on --success (#1a9c6d, shade 6) with --success-soft (#e6f7f0) as shade 0 — the
// badge-active/badge-available fills in the mockups. Same construction as `primary`.
const success = [
  "#e6f7f0",
  "#c8ecdc",
  "#a3dfc5",
  "#74cea7",
  "#4bbf8e",
  "#2fae7b",
  "#1a9c6d",
  "#15855c",
  "#116d4b",
  "#0d563b",
] as const;

// Centred on --danger (#d64545, shade 6) with --danger-soft (#fbe9e9) as shade 0 — badge-expired,
// the danger zone and btn-danger-outline (whose #f0c9c9 border is shade 1). Also replaces the
// auth pages' former `c="red"` (Mantine's #fa5252) for error text.
const danger = [
  "#fbe9e9",
  "#f0c9c9",
  "#e8a8a8",
  "#e18585",
  "#dc6666",
  "#d95353",
  "#d64545",
  "#bd3a3a",
  "#a02f2f",
  "#832525",
] as const;

export const theme = createTheme({
  primaryColor: "primary",
  // Both schemes pinned to shade 6 rather than Mantine's default { light: 6, dark: 8 } — light is
  // the only scheme this story wires up (forceColorScheme="light" in App.tsx), and a single number
  // keeps the primary-shade story consistent if dark mode is ever turned on without a design pass.
  primaryShade: 6,
  colors: { primary, accent, success, danger },
  fontFamily,
  headings: { fontFamily },
  defaultRadius: "md",
  radius: {
    xs: "4px",
    sm: "8px",
    // Buttons and inputs use theme.defaultRadius ("md") unless a component passes its own
    // `radius` prop — mockups/style.css's .btn/.field input are 8–9px; "~10px" per GL-121.
    md: "10px",
    // Cards (AuthCard, and later the dashboard/list-detail cards) pass radius="lg" explicitly to
    // reach this — mockups/style.css's --radius (14px), the one thing a shared "md" couldn't also
    // be without conflating two different mockup values into one theme key.
    lg: "14px",
    xl: "20px",
  },
  shadows: {
    xs: "0 1px 2px rgba(36, 31, 54, 0.04)",
    sm: "0 1px 2px rgba(36, 31, 54, 0.04)",
    md: "0 1px 2px rgba(36, 31, 54, 0.04), 0 8px 24px rgba(36, 31, 54, 0.06)",
    lg: "0 1px 2px rgba(36, 31, 54, 0.04), 0 8px 24px rgba(36, 31, 54, 0.06)",
    xl: "0 1px 2px rgba(36, 31, 54, 0.04), 0 8px 24px rgba(36, 31, 54, 0.06)",
  },
  components: {
    // The mockups have one `.badge`: sentence case, soft fill. Mantine's default is uppercase,
    // which three page agents handled three ways (Batch 43 review, S2) — settled here.
    Badge: { defaultProps: { variant: "light", tt: "none" } },
  },
  other: {
    bg: "#f6f5fb",
    surface: "#ffffff",
    border: "#e4e1f0",
    text: "#241f36",
    textMuted: "#6b647f",
  },
});

// Overrides Mantine's own --mantine-color-body/--mantine-color-text/--mantine-color-default-border (baseline.css already applies
// both to <body>, so this alone satisfies GL-121's "body background/text" requirement with no
// hand-written CSS) and adds --gl-* aliases for `other`'s remaining values, for the few call sites
// that need a CSS custom property rather than a theme prop (AuthCard's page background gradient).
export const cssVariablesResolver: CSSVariablesResolver = (resolvedTheme) => ({
  variables: {
    "--mantine-color-body": resolvedTheme.other.bg,
    "--mantine-color-text": resolvedTheme.other.text,
    // Every Input, Paper withBorder, Divider and Table border in one place — mockups' --border,
    // not Mantine's gray-4 (Batch 42 review, H3).
    "--mantine-color-default-border": resolvedTheme.other.border,
    // `c="dimmed"` and `c="var(--gl-text-muted)"` are the same grey (Batch 43 review, S3).
    "--mantine-color-dimmed": resolvedTheme.other.textMuted,
    "--gl-bg": resolvedTheme.other.bg,
    "--gl-surface": resolvedTheme.other.surface,
    "--gl-border": resolvedTheme.other.border,
    "--gl-text": resolvedTheme.other.text,
    "--gl-text-muted": resolvedTheme.other.textMuted,
  },
  light: {},
  dark: {},
});
